### ISSUE TITLE
Serach functionality is not working on server side pagination.

### ISSUE THREAD

**Issue by bhushan90** [ti-ka/ti-grid#11]
-Search functionality is on working  when server side pagination is done on the grid.
-Please find the aatched doc.
![image](https://user-images.githubusercontent.com/22069932/49289655-71865400-f4ca-11e8-889e-0951fc900cab.png)

**Comment by ti-ka** [comment]
On your `(gridStateChanged)` configuration, you can loop through the columns to get the filter.

```
