### ISSUE TITLE
bind array of data

### ISSUE THREAD

**Issue by Chindara** [ti-ka/ti-grid#9]
cannot bind an array of data to the grid. binding url works well. I want to bind an array.

**Comment by NunoChumbo** [comment]
<ti-grid [columns]="columns" [rows]="yourarray">
</ti-grid>

**Comment by Chindara** [comment]
there is not property as "rows".

columns: IColumn[];

**Comment by ti-ka** [comment]
Yes, there is a "rows" property:
https://github.com/ti-ka/ti-grid/blob/0e208ccfffc8b535b80335329811dfaffcd36f7e/projects/ti-grid/src/lib/ti-grid.component.ts#L14

Rows is basically data array. Are you using the `[url]`?

**Comment by Chindara** [comment]
Thanks for the response. It works as expected. I was using the `[url]`.

**Comment by Chindara** [comment]
``

**Comment by Chindara** [comment]
Thanks for the response. It works as expected. I was using the `[url]`.
